# Generated by Django 5.1.4 on 2026-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("job_key", models.CharField(max_length=64, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("scheduled_call", "Scheduled call"), ("crm_sync", "CRM sync")],
                        max_length=32,
                    ),
                ),
                ("object_id", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "django_scheduler_job",
                "ordering": ["next_run_at", "id"],
            },
        ),
    ]
