# Generated by Django 5.1.4 on 2026-04-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255)),
                ('file_storage', models.CharField(blank=True, max_length=1024, null=True)),
                ('text_to_speech', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'campaign_recording',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Blocklist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('expires', models.DurationField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('phone_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=16, null=True)),
                ('hits', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'admin_blocklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('call_id', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calls',
                'ordering': ['-timestamp', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=500)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_type', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_state', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_subtype', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign_language', models.CharField(blank=True, max_length=255, null=True)),
                ('segment_by', models.CharField(blank=True, max_length=255, null=True)),
                ('locate_by', models.CharField(blank=True, max_length=255, null=True)),
                ('include_special', models.CharField(blank=True, max_length=255, null=True)),
                ('target_ordering', models.CharField(blank=True, max_length=255, null=True)),
                ('target_shuffle_chamber', models.BooleanField(default=True)),
                ('target_offices', models.CharField(blank=True, max_length=255, null=True)),
                ('call_maximum', models.SmallIntegerField(blank=True, null=True)),
                ('allow_call_in', models.BooleanField(default=False)),
                ('allow_intl_calls', models.BooleanField(default=False)),
                ('prompt_schedule', models.BooleanField(default=False)),
                ('status_code', models.SmallIntegerField(default=0)),
                ('embed', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign_campaign',
                'ordering': ['-status_code', '-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignAudioRecording',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'campaign_audio_recordings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'campaign_phone_numbers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignTarget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'campaign_target_sets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LegacyUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('openid', models.CharField(blank=True, max_length=255, null=True)),
                ('activation_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role_code', models.SmallIntegerField(default=1)),
                ('status_code', models.SmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'user_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('subscribed', models.BooleanField(default=True)),
                ('time_to_call', models.TimeField(blank=True, null=True)),
                ('last_called', models.DateTimeField(blank=True, null=True)),
                ('num_calls', models.IntegerField(default=0)),
                ('phone_number', models.CharField(blank=True, max_length=64, null=True)),
                ('job_id', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'schedule_call',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('phone_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=64, null=True)),
                ('from_number', models.CharField(blank=True, max_length=16, null=True)),
                ('twilio_id', models.CharField(blank=True, max_length=40, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('direction', models.CharField(blank=True, max_length=25, null=True)),
                ('queue_delay', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'calls_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyncCampaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_id', models.CharField(blank=True, max_length=36, null=True)),
                ('created_time', models.DateTimeField(blank=True, null=True)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.CharField(default='hourly', max_length=25)),
                ('crm_id', models.CharField(blank=True, max_length=40, null=True)),
                ('crm_key', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'sync_campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'campaign_target',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TargetOffice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latlon', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'campaign_target_office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TwilioPhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('twilio_sid', models.CharField(blank=True, max_length=64, null=True)),
                ('twilio_app', models.CharField(blank=True, max_length=64, null=True)),
                ('call_in_allowed', models.BooleanField(default=False)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'campaign_phone',
                'managed': False,
            },
        ),
    ]
