# Generated by Django 5.1.4 on 2026-04-17 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiorecording_blocklist_call_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncCall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('saved', models.BooleanField(default=False)),
                ('crm_message', models.CharField(blank=True, max_length=255, null=True)),
                ('call', models.ForeignKey(db_column='call_id', on_delete=django.db.models.deletion.CASCADE, related_name='sync_records', to='core.call')),
            ],
            options={
                'db_table': 'sync_call',
            },
        ),
    ]
