formatter:
- clippy: {}
- histo: {}
tools:
  r2c.bandit:
    ignore:
    - B101
    - B104
    - B105
    - B106
    - B107
    - B108
    - B112
    - B303
    - B310
    - B311
    - B403
    - B404
    - B405
    - B406
    - B407
    - B408
    - B409
    - B410
    - B603
    - B604
    - B606
    - B607
    - B608
  r2c.flake8:
    ignore:
    - A003
    - E117
    - E127
    - E122
    - E252
    - E123
    - F401
    - E224
    - E742
    - E115
    - E131
    - E743
    - E116
    - E266
    - E231
    - E201
    - E713
    - E401
    - E221
    - E731
    - E121
    - E502
    - E305
    - B010
    - E275
    - E222
    - E301
    - E251
    - E402
    - E303
    - B001
    - W391
    - E712
    - F406
    - E261
    - E228
    - E223
    - E133
    - E242
    - E304
    - E302
    - E227
    - E128
    - E704
    - E211
    - E274
    - E225
    - E702
    - W291
    - W504
    - E703
    - E226
    - E241
    - E111
    - E202
    - E129
    - E306
    - B009
    - E101
    - E501
    - E714
    - W293
    - E265
    - E114
    - E741
    - E125
    - E126
    - E262
    - E721
    - W191
    - E203
    - E701
    - W503
    - E273
    - E711
    - W292
    - E124
    - E271
    - E272
  r2c.flask:
    ignore: []
  r2c.requests:
    ignore: []
